# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Hello my honey JEE
email: bo-gun@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
 This website is for all about the motorcycle and its parts that related to.
  
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://bikemaniaclub.com" # the base hostname & protocol for your site

github_username:  qhrjsdl

# Build settings
markdown: kramdown
